### ISSUE TITLE
Going to the profile make the menu entrances disappear

### ISSUE THREAD

**Issue by alessandrobelli** [openqda/openqda#28]
I'm not sure if this bug present itself only offline (vite issue?) or also on production, but it's something happening frequently to me.
Tested in Firefox and Safari.

I reproduce it offline with the following:
1. Login
2. click on projects
3. right after click on profile

Gif preview:
![Screen Recording 2024-05-22 at 11 06 21](https://github.com/openqda/openqda/assets/3796324/9cbdc561-a65d-4056-a828-252e5ad13148)

**Comment by jankapunkt** [comment]
Client issue. Will fix it.

**Comment by jankapunkt** [comment]
fixed in #29
