### ISSUE TITLE
CSV export doesn't work

### ISSUE THREAD

**Issue by hohse** [openqda/openqda#31]
I got an email from a user (student at Uni Bremen) with the following text "[J]etzt stelle ich fest, dass ich meine Ergebnisse nicht als CSV exportieren kann. Wisse[e!]n Sie vielleicht, woran dies liegen könnte?".
The problem is that he can not export his results (I assume he means coded text passages) as a CSV file.

I checked and encountered the same problem. In the analysis section for the "List" option, I can select documents and codes, but the "Export CSV" button is greyed out and can not be clicked. Code portrait and Wordcloud seem to work fine, but the CSV-button is also greyed out and unclickable there.

I don't know what system the student is running, but I'm on MacOS Sonoma 14.5 and I'm using Chrome Version 124.0.6367.208.

**Comment by jankapunkt** [comment]
@hohse is this fixed on our staging system? Can I close it?

**Comment by hohse** [comment]
@jankapunkt Yes, it's fixed everywhere and can be closed.
